# Walking through a SpikeInterface pipeline {.unnumbered}
\
In this chapter, we will implement a spike sorting pipeline from start to finish, using SpikeInterface.
We will go through the key steps at a high level here, and develop the theory and add more complex methods and
use cases in the following chapters.

In this walkthrough, we will use a short example dataset available for download [here]().
This dataset contains 2.5 seconds of data recorded on 384 channels, with channels
located on the middle two shanks of a 4-shank Neuropixels probe, acquired in SpikeGLX.

We will load and preprocess the data, run spike sorting and compute quality metrics
for assessing the sorting output.

Let's get started!
 
## Data Loading and Exploration

### Data Loading

First, we will load the data, currently saved on our hard drive, into Python.

SpikeInterface can load data from many different types of acquisition systems, using functions within its [extractors module](https://spikeinterface.readthedocs.io/en/stable/modules/extractors.html). As our data is from SpikeGLX, we will use the `read_spikeglx` method.

We need to tell SpikeInterface where the data is, and what [data stream](concept-notes.qmd#spikeglx-streams)💡 we want to load. A stream refers to a continuous recording of voltage signals from a specific set of channels, sampled at a fixed rate. SpikeGLX saves different streams to separate files depending on the frequency band and channel type. Streams written by SpikeGLX can include the action potential (AP) band, local field potential (LF) band and a sync stream (depending on the version).

Because we want to load the AP data stream for spike sorting, we pass `"imec0.ap"`.

```{python}
import spikeinterface.extractors as si_extractors

# This should be the path to the folder contaning
# the data. On Windows, you may need to preprend
# r to the string e.g. r"C:\my\path"
path_to_data_folder = "data/pipeline-walkthrough"

recording = si_extractors.read_spikeglx(
    path_to_data_folder,
    stream_id="imec0.ap"
)

print(recording)
```

SpikeInterface uses 'lazy loading', which means at this stage no data is actually loaded into memory. Data is only loaded when we request it (e.g. for visualisation, or spike sorting)
and only the requested chunk is loaded. This makes operations very fast as we do not need to load
large recordings up-front.

### The Recording object

SpikeInterface extractor functions return the recording as a [Python object](https://www.geeksforgeeks.org/python/python-classes-and-objects/), which contains many useful methods for exploring the recording metadata as well as accessing the underlying data. In our case, recording is a `SpikeGLXRecordingExtractor` recording object.

The [SpikeInterface API Documentation](https://spikeinterface.readthedocs.io/en/latest/api.html) is a useful resource for looking up methods associated with an object and their arguments.  In Spikeinterface, all recordings [inherit](concept-notes.qmd#inheritence)💡 from the `BaseRecording`, so checking out the [API docs for BaseRecording](https://spikeinterface.readthedocs.io/en/latest/api.html#spikeinterface.core.BaseRecording) gives us iformation about all recording objects. 

You can also use Python's `dir()` functoin to see all attributes and methods associated with any Python object.

```{python}

print(
    [method for method in dir(recording) if method.startswith("get")]
)
```


:::{.callout-tip}
### Some things to try 

This is a good time to explore the recording object using the API docs. Have a go at the following:

- Print the locations of all channels on the probe.
- Print the time vector associated with the recording.
- Use `get_traces()` to retrieve a segment of raw data as a NumPy array. What are its dimensions?
:::

### Visualising the probe

There are many brands of recording probes used in extracellular electrophysiology (e.g. 
[Neuropixels](https://www.neuropixels.org/), 
[Cambridge Neurotech](https://www.cambridgeneurotech.com/neural-probes) or
[NeuroNexus](https://www.neuronexus.com/products/electrode-arrays/)
). There are many models, which come in complex and varied geometries and channel arangements

Under the hood, SpikeInterface uses the ProbeInterface package to load many different types of probe. In our case, it automatically identifie and loaded a Neuropixels 2 (NP2) probe.

It is important to check that the probe has loaded as expected, and that the geometry matches how it was set up in your acquisition software. We can plot the probe to confirm it loaded correctly:

```{python}
from probeinterface.plotting import plot_probe
import matplotlib.pyplot as plt

probe = recording.get_probe()

plot_probe(probe)
plt.show()

```

As expected, we have a 4-shank Neurpixels probe in which all the recording channels are located in the middle two shanks. The argument [`show_contact_ids`](https://probeinterface.readthedocs.io/en/main/api.html#probeinterface.plotting.plot_probe) can also be used to display the contact IDs, to double check the exact location of each contact.

### Visualising the data

Electrophysiological recordings are susceptible to contamination from multiple noise sources: electrical interference, mechanical noise caused by probe movement, and artefacts arising from hardware defects or poor contact.

As such, it is important to visualise the data, especially after preprocessing, to check the data quality. First, lets's plot one second of data from our raw recording:

```{python}
import spikeinterface.widgets as si_widgets

start_time = recording.get_times()[0]

si_widgets.plot_traces(
    recording,
    time_range=(start_time, start_time + 0.1),
    return_in_uV=True,
    order_channel_by_depth=True
)
plt.show()
```


`return_in_uV` to ensure the data is returned in interpretable units (microvolts), as by default 
most electrophysiological recordings are [stored as unitless `int16` values](concept-notes.qmd#data-storage-in-int16-and-scaling-to-uv)💡.

`order_channel_by_depth` is used as the default ordering of channels on the probe is not always by depth, meaning the order is scrambled on the plot.

:::{.callout-tip}
### Tip
In general when working with raw data, you can use [`recording.get_channel_locations()`](https://spikeinterface.readthedocs.io/en/latest/api.html#spikeinterface.core.BaseRecording.get_channel_locations) to inspect the default channel ordering of the 
channels, and [`order_channels_by_depth()`](https://spikeinterface.readthedocs.io/en/stable/api.html#spikeinterface.core.order_channels_by_depth) function can be used to get the indicies for reordering.

:::

As we can see - the raw data looks terrible! It is severely contaminated, mostly by electrical noise. We will need to preprocess it to tidy it up.

## Preprocessing

Below, we will apply three key preprocessing steps: 

**phase_shift** : corrects a hardware artefact in the Neuropixels probe 
which causes small shifts between the recording time across nearby channels.

**bandpass_filter** : removes high and low frequency oscillations from the data. It is applied to each channel separately. 

**commmon_reference** : removes noise spikes that appear as verticle stripes across the data. It is applied across channels separately at each timepoint.

To preprocess the data, we will pass our recording object into functions that return a new, recording object. e.g. ```filtered_recording = bandpass_filter(recording)```. We can do this for every step in the preprocessing chain:

```{python}
import spikeinterface.preprocessing as si_prepro

phase_shift_recording = si_prepro.phase_shift(recording)
filtered_recording = si_prepro.bandpass_filter(
    phase_shift_recording, freq_min=300, freq_max=6000
)
cmr_recording = si_prepro.common_reference(
    filtered_recording, operator="median"
)
```

In SpikeInterface, the preprocessing is applied almost instantly due to the 'lazy' loading
mentioned earlier. When we apply the preprocessing function, we only really just change the metadata associated with the recording, the data is not actually changed at this stage.

Only when we get the data (e.g. in `plot_traces`, or with `get_traces()` or when saving the data) is the data preprocessed in the requested chunk. This makes operating very fast!

Now we are ready to plot the data:

```{python}

si_widgets.plot_traces(
    cmr_recording,
    time_range=(start_time, start_time + 0.1),
    return_in_uV=True,
    order_channel_by_depth=True
)
plt.show()

```

As you can see, it is much cleaner and we can see action potentials firing! However, there does seem to be an artefact, small gaps in the action potential waveform. We will investigate these in the next section.

### Splitting the data by shank

You might notice the data in the above image looks slightly strange. All spikes have predictable gaps between them, we can see this clearly if we zoom into a single action potential waveform:

```{python}
si_widgets.plot_traces(
    cmr_recording,
    time_range=(23.923, 23.928),
    return_in_uV=True,
    order_channel_by_depth=True,
)
ax = plt.gca()
ax.set_ylim(200, 300)
plt.show()
```

:::{.callout-note icon=false}
### Discuss
Look carefully at the plot above. Why do you think there are predictable gaps in the signal every two channels?
:::

::: {.callout-note collapse="true"}
### Click to reveal the answer

Our recording channels are located on two shanks, however we have plot all recording channels
together. The channels on different shanks have the same y-position, so they are plot
next to eachother, but different x-positions. 

This means that the AP recorded on one shanks channels is interleaved with blank channels from the other shank. 

:::

We can solve this by spliting the recording by shank with the `groups` property. When SpikeInterface loads the data, it will automatically assign different shanks to different groups:

```{python}

split_recording = cmr_recording.split_by("group")
print(
    split_recording
)
```

We can plot both shanks separately:

```{python}

fig, ax = plt.subplots(1, 2)

for shank_idx, shank_recording in split_recording.items():

    si_widgets.plot_traces(
        shank_recording,
        time_range=(start_time, start_time + 0.1),
        return_in_uV=True,
        order_channel_by_depth=True,
        ax=ax[shank_idx]
    )
    ax[shank_idx].set_title(f"Shank: {shank_idx}")

plt.show()
```

```{python}

si_widgets.plot_traces(
    split_recording[0],
    time_range=(23.923, 23.926),
    return_in_uV=True,
    order_channel_by_depth=True,
    mode="map"
)
ax = plt.gca()
ax.set_ylim(200, 300)
plt.show()
```

Much better!

Now we have our preprocessed data, and have visually confirmed the data quality is good, we are ready to perform spike sorting! 

:::{.callout-tip}
### Additional things to try
- How does the data look using `median` vs. `mean` for `common_average`?
- What happens if you set the bandpass filter minimum cutoff to zero? What frequencies are including now? Or set the maximum cutoff to 15000?
- Set `return_in_uV=False`. Does the data look much different?
- Save the data to disk with the Recording objects `.save` attribute
- Use `get_traces()` with and without `return_in_uV` as `True` and `False` to inspect the data type.
- Perform spike detection (e.g. absolute threshold method) on the preprocessed data obtained with `get_traces()`

:::



## Section 2: Sorting

Now we are ready to move onto spike sorting. In practice, a spike sorter is an algorithm to which we pass our recording, and it detects the spikes and assigns them to units.

In SpikeInterface, running a sorter is quite simple. Today, we will run Kilosort4, and we can do it with a single function call:

```{python}
from pathlib import Path
import spikeinterface.sorters as si_sorters

sorter_folder = Path("kilosort4_output")
sorter_output_folder = sorter_folder / "sorter_output"

if sorter_output_folder.exists():
    sorting = si_extractors.read_kilosort(sorter_output_folder)
else:
    sorting = si_sorters.run_sorter(
        "kilosort4",
        cmr_recording,
        folder=sorter_folder,
        remove_existing_folder=True,
        do_CAR=False,
        highpass_cutoff=0.1,
    )

print(sorting)
```

You will see the sorting output written to disk. This contains all of the output files of the sorter, and its organisation is sorter-dependent.

We also have a lot of the information output by the sorter in a `sorting` object. We can get it, for example:

```{python}

spikes = sorting.to_spike_vector()
print(spikes[:10])
```


:::{.callout-tip}
### Some things to try 
 - more investigation of spike vector
 - get unit ids
 - get unit spike train
 - plot a histogram? (probs not time)
:::

## Section 4: Postprocessing

This will be a whitestop tour. We will go into much more detail later. What is teh purpose of this.

### create sorting analyzer

In SPikeInterface, the main construct for work with postprocessing of spike sorting outputs is the `SortingAnalzyer` object. We can create the `SortingAnalzyer` by passing the sorting output and recording to a sorting XXX.

TODO: give overview. We will choose spikes, cut out waveform, compute templates etc. amplitudes.
basically extract the features of the detected APs.

We can create a `SortingAnalyzer` we need to pass our preprocessing `recording` and the `sorting` output:

```{python}
from spikeinterface import create_sorting_analyzer

analyzer = create_sorting_analyzer(
    sorting=sorting,
    recording=recording
)
```

Using this sorting analyzer interface, we will compute all of the
postprocessing we need to assess the quality of our sorting.

:::{warning}
Some sorters will output their own waveforms, templates, amplitudes ETC (for example, Kilosort has a `templates.npy` file containnig the templates it generated during sorting).

These are not loaded by SpikeInterface. Instead, the sorting analzyer will always recompute these features directly from the passed `recording`.
:::

### compute spikes

In our sorting, we can have many many detected spikes. This may be in the order of millios of spikes for an hour long recording.

To process all of these spikes would be computationally intensive, and give diminishing gains. We can instead sample a subset of spikes. In this step, we will randomly select spikes uniformly from the recording with the `max_spikes_per_unit` argument.

```{python}
analyzer.compute(
    "random_spikes",
    method="uniform",
    max_spikes_per_unit=500,
)
```

to access...

```{python}
spike_indices = analyzer.get_extension("random_spikes").data["random_spikes_indices"]
spike_times = spike_indices / recording.get_sampling_frequency()

print(spike_times)
```

### waveforms

Next, we will extract the waveforms from the preprocessed data.

```{python}
analyzer.compute("waveforms", ms_before=1.0, ms_after=2.0)

waveforms = analyzer.get_extension("waveforms").data["waveforms"]

print(waveforms.shape)

plt.imshow(waveforms[12, :, :].T)
plt.show()
```

The waveforms array is three dimensional `(num waveforms, num samples, num channels)`. Indexing the first dimension will
get us the 2d waveform. We can transpose the matrix so that it is num channels x num timepoints and plot it ourselves to confirm by plotting the raw array.

SOME THINGS TO TRY
1) PLOT SOME OTHER WAVEFORMS
2) PLOT SOME WAVEFORMS FROM UNIT XXX USING THE SPIKE_CLUSTER INFORMATION
3) COMPUTE THE MEAN OF ALL WAVEFORMS xxx

### templates

The template is a representative wavecform from a putative neuron. Often, it is computed as the average
waveform from all of the spikes that were assigned to a unit i.e. thought to be fired from the same neuron.

We can compute the extension and access the templates with:

For all these, don't forget WHY we aer doing them

```{python}
analyzer.compute("templates")

templates = analyzer.get_extension("templates").data["average"]

print(
    templates.shape
)
```

SPIKEINTERFACE PLOT
```
si_widgets.plot_unit_templates(analyzer, unit_ids=[0])
plt.show()
```

### amplitudes

There are a number of different features we can compute from our waveforms and templates,
which are useful for quality assessment. We will explore more of these in detail in XXX.

One of thes features i the spike amplitude. It is assumed that the amplitud eof a neuron shouold
be imila across the recording. If the amplitude decreases, for example, acroess the ession, maybe the neuron dead.

```
amplitudes = analyzer.get_extension("spike_amplitudes").data["amplitudes"]

print(amplitudes)
```

This gives a list of amplitudes, one for every spike. We could get the amplitudes
for a specific unit with:

XXX

and plot across time
XXX

## Section 5: Manual Curation in spikeinterface-gui










